[cv]
name = "张雨璇"
email = " yuxuanzzz1999@outlook.com"
phone = "(+86) 150-0918-3683"
# 路径
avatar = ""

[[educations]]
school = "云南大学"
major = "环境设计"
degree = "硕士"
date = "2023.9 - 2026.7"

[[educations]]
school = "咸阳师范学院"
major = "环境设计"
degree = "本科"
date = "2017.9 - 2021.7"

[[projects]]
name = "2023年云南大学常态化社会实践项目"
date = " 2023.09—2023.12"
desc = "本项目从环境心理学视角出发，对昆明市盲哑学校的物理空间进行调研与分析，旨在提出一套针对视障与听障学生特殊需求的人性化设计改造方案，以提升其空间使用体验与心理健康水平。"
points = ["组织并实施现场调研，通过行为观察与访谈，系统分析空间使用痛点。", "主笔撰写最终调研报告，项目荣获校级一等奖"]

[[projects]]
name = "云南省教育厅科学研究基金项目"
date = "2024.04—2025.09"
desc = "本省级基金项目立足于乡村振兴国家战略，探究艺术介入与设计赋能在于会泽县乡村建设中的具体路径与模式，旨在为乡村文化振兴与空间活化提供理论依据与实践案例"
points = [ "作为核心成员，独立负责并完成项目的理论框架构建工作", "参与会泽县实地调研，系统收集村落空间与文化背景等关键数据",]

[[projects]]
name = "云南大学第四届专业学位研究生实践创新项目"
date = ""2024.9—2024.12"
desc = "本项目以泉州“刺桐古城”红砖文化遗产为灵感来源，将其独特的视觉元素与文化内涵融入安溪铁观音的茶叶包装设计，旨在打造兼具地域文化特色与市场吸引力的品牌形象。"
points = ["作为核心成员，参与构思项目研究框架并撰写立项申请书", "主导项目的设计研究与概念开发，系统梳理了红砖文化的视觉符号体系"]

[[internships]]
company = "苏州博物馆"
jobtitle = "陈列展览部实习生"
date = "2025.2 - 2025.7"
points = ["深度参与并执行“从拙政园到莫奈花园”及“张占占个展”等重点展览的形式设计落地全流程"]

[[internships]]
company = "中国近现代新闻出版博物馆"
jobtitle = "展陈与宣教部实习生"
date = "2024.7 - 2024.9"
points = ["独立撰写报纸中的时代记忆展展陈大纲与展签，参与展览内容策划。", " 独立完成第十届博博会临展手册等关键宣传物料的设计与排版"]

[[Research and Awards]]
name = "大众文艺（省刊）"
date = "2025年18期"

[[Research and Awards]]
name = "第六届东方创意之星创新设计大赛（银奖）"
date = "2025.8"

[[Research and Awards]]
name = "中国好创意(第十九届)暨全国数字艺术设计大赛（优秀奖）"
date = "2025.8"


[[skills]]
name = "设计软件"
desc = "Illustrator、Photoshop、Figma、InDesign、AutoCAD、SketchUp"

[[skills]]
name = "语言"
desc = "中文, 英语
